# Generated by Django 5.1.2 on 2024-10-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file_alter_document_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='typed_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
